### ISSUE TITLE
🤔 I guess I catalog and rate the movies I've seen as issues?

### ISSUE THREAD

**Issue by shnewto** [DaveyLaser/moviebuff#1]
I saw Deadpool 2. It gets 🌟 out of 🌟 because it was a movie, as advertised.

**Comment by shnewto** [comment]
That's 1 out of 1 stars.

**Comment by DaveyLaser** [comment]
Lol! KISS! I let my users build the app!
JK, it's a little practice app I'm throwing together for a thing.
